site_name: Userverse Documentation
theme:
  name: material

nav:
  - Introduction: index.md
  - Configuration: configuration.md
  - Production Deployment: production.md
  - Testing: testing.md
  - FAQ: faq.md
