site_name: Userverse Documentation
theme:
  name: material

nav:
  - Introduction: index.md
  - Quick Start Guide: quick_start.md
  - Registration Guide:
      - User Registration: user_registration.md
      - Organization Registration: organization_registration.md
  - Settings Guide:
      - Adding Users to Organizations: add_users_to_organizations.md
      - Managing Roles: manage_roles.md
      - Updating Organization Details: update_organization_details.md
  - User-Organization Linking:
      - Inviting Users: invite_users.md
      - Joining Organizations: join_organizations.md
      - Removing Users: remove_users.md
  - Reports and Analytics:
      - User Activity Reports: user_activity_reports.md
      - Organization Reports: organization_reports.md
  - FAQ: faq.md